const dataSets = {
  "a4-a": [
    { id: 10, card: "Entei ex", bucket: "Suicune", rarity: "◊◊◊◊" },
    { id: 25, card: "Raikou ex", bucket: "Suicune", rarity: "◊◊◊◊" },
    { id: 33, card: "Mismagius", bucket: "Suicune", rarity: "◊◊" },
    { id: 75, card: "Latios", bucket: "Suicune", rarity: "☆" },
    { id: 76, card: "Phanpy", bucket: "Suicune", rarity: "☆" },
    { id: 78, card: "Jumpluff ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 79, card: "Entei ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 80, card: "Suicune ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 81, card: "Raikou ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 82, card: "Poliwrath ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 83, card: "Whitney", bucket: "Suicune", rarity: "☆☆" },
    { id: 84, card: "Traveling Merchant", bucket: "Suicune", rarity: "☆☆" },
    { id: 85, card: "Morty", bucket: "Suicune", rarity: "☆☆" },
    { id: 86, card: "Jumpluff ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 87, card: "Entei ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 88, card: "Raikou ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 89, card: "Poliwrath ex", bucket: "Suicune", rarity: "☆☆" },
    { id: 90, card: "Suicune ex", bucket: "Suicune", rarity: "☆☆☆" },
    { id: 91, card: "Chimchar", bucket: "Suicune", rarity: "✷" },
    { id: 92, card: "Monferno", bucket: "Suicune", rarity: "✷" },
    { id: 94, card: "Golduck", bucket: "Suicune", rarity: "✷" },
    { id: 95, card: "Krabby", bucket: "Suicune", rarity: "✷" },
    { id: 97, card: "Pyukumuku", bucket: "Suicune", rarity: "✷" },
    { id: 98, card: "Gible", bucket: "Suicune", rarity: "✷" },
    { id: 99, card: "Gabite", bucket: "Suicune", rarity: "✷" },
    { id: 100, card: "Paldean Wooper", bucket: "Suicune", rarity: "✷" },
    { id: 101, card: "Infernape ex", bucket: "Suicune", rarity: "✷✷" },
    { id: 103, card: "Garchomp ex", bucket: "Suicune", rarity: "✷✷" },
    { id: 104, card: "Paldean Clodsire ex", bucket: "Suicune", rarity: "✷✷" },
    { id: 105, card: "Mantyke", bucket: "Suicune", rarity: "♛" }
  ],
  "a4": [
    { id: 45, card: "Gyarados", bucket: "Lugia", rarity: "◊◊◊" },
    { id: 71, card: "Raikou", bucket: "Ho-Oh", rarity: "◊◊◊" },
    { id: 128, card: "Klinklang", bucket: "Ho-Oh", rarity: "◊◊◊" },
    { id: 161, card: "Hiker", bucket: "Ho-Oh", rarity: "◊◊" },
    { id: 163, card: "Bellossom", bucket: "Lugia", rarity: "☆" },
    { id: 165, card: "Cyndaquil", bucket: "Lugia", rarity: "☆" },
    { id: 166, card: "Magby", bucket: "Ho-Oh", rarity: "☆" },
    { id: 169, card: "Octillery", bucket: "Lugia", rarity: "☆" },
    { id: 175, card: "Wobbuffet", bucket: "Lugia", rarity: "☆" },
    { id: 177, card: "Spinarak", bucket: "Ho-Oh", rarity: "☆" },
    { id: 178, card: "Murkrow", bucket: "Lugia", rarity: "☆" },
    { id: 181, card: "Sentret", bucket: "Ho-Oh", rarity: "☆" },
    { id: 182, card: "Hoothoot", bucket: "Ho-Oh", rarity: "☆" },
    { id: 185, card: "Blissey", bucket: "Ho-Oh", rarity: "☆" },
    { id: 186, card: "Shuckle ex", bucket: "Lugia", rarity: "☆☆" },
    { id: 188, card: "Kingdra ex", bucket: "Lugia", rarity: "☆☆" },
    { id: 189, card: "Lanturn ex", bucket: "Lugia", rarity: "☆☆" },
    { id: 191, card: "Donphan ex", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 192, card: "Crobat ex", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 194, card: "Skarmory ex", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 195, card: "Lugia ex", bucket: "Lugia", rarity: "☆☆" },
    { id: 197, card: "Lyra", bucket: "Lugia", rarity: "☆☆" },
    { id: 198, card: "Silver", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 199, card: "Fisher", bucket: "Lugia", rarity: "☆☆" },
    { id: 200, card: "Jasmine", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 201, card: "Hiker", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 202, card: "Shuckle ex", bucket: "Lugia", rarity: "☆☆" },
    { id: 203, card: "Kingdra ex", bucket: "Lugia", rarity: "☆☆" },
    { id: 204, card: "Lanturn ex", bucket: "Lugia", rarity: "☆☆" },
    { id: 205, card: "Espeon ex", bucket: "Lugia", rarity: "☆☆" },
    { id: 207, card: "Crobat ex", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 208, card: "Umbreon ex", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 209, card: "Skarmory ex", bucket: "Ho-Oh", rarity: "☆☆" },
    { id: 210, card: "Ho-Oh ex", bucket: "Ho-Oh", rarity: "★★★" },
    { id: 212, card: "Yanma", bucket: "Ho-Oh", rarity: "✷" },
    { id: 213, card: "Flareon", bucket: "Ho-Oh", rarity: "✷" },
    { id: 214, card: "Magikarp", bucket: "Lugia", rarity: "✷" },
    { id: 217, card: "Magnemite", bucket: "Lugia", rarity: "✷" },
    { id: 218, card: "Magneton", bucket: "Lugia", rarity: "✷" },
    { id: 219, card: "Jolteon", bucket: "Lugia", rarity: "✷" },
    { id: 220, card: "Misdreavus", bucket: "Ho-Oh", rarity: "✷" },
    { id: 222, card: "Primeape", bucket: "Ho-Oh", rarity: "✷" },
    { id: 225, card: "Nidoqueen", bucket: "Lugia", rarity: "✷" },
    { id: 226, card: "Nidoran♂", bucket: "Ho-Oh", rarity: "✷" },
    { id: 227, card: "Nidorino", bucket: "Ho-Oh", rarity: "✷" },
    { id: 229, card: "Sneasel", bucket: "Lugia", rarity: "✷" },
    { id: 230, card: "Lickitung", bucket: "Ho-Oh", rarity: "✷" },
    { id: 231, card: "Eevee", bucket: "Ho-Oh", rarity: "✷" },
    { id: 232, card: "Yanmega ex", bucket: "Ho-Oh", rarity: "✷✷" },
    { id: 235, card: "Glaceon ex", bucket: "Lugia", rarity: "✷✷" },
    { id: 237, card: "Mismagius ex", bucket: "Ho-Oh", rarity: "✷✷" },
    { id: 239, card: "Lickilicky ex", bucket: "Ho-Oh", rarity: "✷✷" },
    { id: 240, card: "Ho-Oh ex", bucket: "Ho-Oh/Lugia", rarity: "♛" },
    { id: 241, card: "Lugia ex", bucket: "Ho-Oh/Lugia", rarity: "♛" }
  ],
  "a3-b": [
    { id: 79, card: "Flareon ex", bucket: "Eevee", rarity: "☆☆" },
    { id: 81, card: "Sylveon ex", bucket: "Eevee", rarity: "☆☆" },
    { id: 84, card: "Snorlax ex", bucket: "Eevee", rarity: "☆☆" },
    { id: 85, card: "Hau", bucket: "Eevee", rarity: "☆☆" },
    { id: 86, card: "Penny", bucket: "Eevee", rarity: "☆☆" },
    { id: 87, card: "Flareon ex", bucket: "Eevee", rarity: "☆☆" },
    { id: 88, card: "Primarina ex", bucket: "Eevee", rarity: "☆☆" },
    { id: 90, card: "Dragonite ex", bucket: "Eevee", rarity: "☆☆" },
    { id: 93, card: "Pinsir", bucket: "Eevee", rarity: "✷" },
    { id: 95, card: "Voltorb", bucket: "Eevee", rarity: "✷" },
    { id: 96, card: "Electrode", bucket: "Eevee", rarity: "✷" },
    { id: 98, card: "Kirlia", bucket: "Eevee", rarity: "✷" },
    { id: 100, card: "Ekans", bucket: "Eevee", rarity: "✷" },
    { id: 102, card: "Farfetch’d", bucket: "Eevee", rarity: "✷" },
    { id: 103, card: "Moltres ex", bucket: "Eevee", rarity: "✷✷" },
    { id: 104, card: "Articuno ex", bucket: "Eevee", rarity: "✷✷" },
    { id: 105, card: "Zapdos ex", bucket: "Eevee", rarity: "✷✷" },
    { id: 107, card: "Eevee Bag", bucket: "Eevee", rarity: "♛" }
  ],
  "a3-a": [
    { id: 76, card: "Buzzwole ex", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 77, card: "Tapu Koko ex", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 78, card: "Lycanroc ex", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 79, card: "Guzzlord ex", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 80, card: "Alolan Dugtrio ex", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 81, card: "Gladion", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 82, card: "Looker", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 83, card: "Lusamine", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 85, card: "Lycanroc ex", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 86, card: "Guzzlord ex", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 87, card: "Alolan Dugtrio ex", bucket: "Buzzwole", rarity: "☆☆" },
    { id: 89, card: "Growlithe", bucket: "Buzzwole", rarity: "✸" },
    { id: 90, card: "Arcanine", bucket: "Buzzwole", rarity: "✸" },
    { id: 91, card: "Froakie", bucket: "Buzzwole", rarity: "✸" },
    { id: 92, card: "Frogadier", bucket: "Buzzwole", rarity: "✸" },
    { id: 94, card: "Jynx", bucket: "Buzzwole", rarity: "✸" },
    { id: 95, card: "Pidgey", bucket: "Buzzwole", rarity: "✸" },
    { id: 96, card: "Pidgeotto", bucket: "Buzzwole", rarity: "✸" },
    { id: 98, card: "Aerodactyl", bucket: "Buzzwole", rarity: "✸" },
    { id: 102, card: "Pidgeot ex", bucket: "Buzzwole", rarity: "✸✸" },
    { id: 103, card: "Nihilego", bucket: "Buzzwole", rarity: "♛" }
  ],
  "a3": [
    { id: 158, card: "Tsareena", bucket: "Solgaleo", rarity: "☆" },
    { id: 160, card: "Alolan Marowak", bucket: "Lunala", rarity: "☆" },
    { id: 161, card: "Turtonator", bucket: "Lunala", rarity: "☆" },
    { id: 163, card: "Pyukumuku", bucket: "Lunala", rarity: "☆" },
    { id: 165, card: "Oricorio", bucket: "Solgaleo", rarity: "☆" },
    { id: 167, card: "Cutiefly", bucket: "Solgaleo", rarity: "☆" },
    { id: 168, card: "Comfey", bucket: "Solgaleo", rarity: "☆" },
    { id: 169, card: "Sandygast", bucket: "Solgaleo", rarity: "☆" },
    { id: 172, card: "Rockruff", bucket: "Solgaleo", rarity: "☆" },
    { id: 174, card: "Minior", bucket: "Lunala", rarity: "☆" },
    { id: 175, card: "Magearna", bucket: "Solgaleo", rarity: "☆" },
    { id: 178, card: "Bewear", bucket: "Lunala", rarity: "☆" },
    { id: 180, card: "Decidueye ex", bucket: "Lunala", rarity: "☆☆" },
    { id: 181, card: "Dhelmise ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 182, card: "Incineroar ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 185, card: "Alolan Raichu ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 186, card: "Lunala ex", bucket: "Lunala", rarity: "☆☆" },
    { id: 187, card: "Passimian ex", bucket: "Lunala", rarity: "☆☆" },
    { id: 189, card: "Solgaleo ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 190, card: "Acerola", bucket: "Lunala", rarity: "☆☆" },
    { id: 191, card: "Ilima", bucket: "Lunala", rarity: "☆☆" },
    { id: 192, card: "Kiawe", bucket: "Lunala", rarity: "☆☆" },
    { id: 193, card: "Guzma", bucket: "Lunala", rarity: "☆☆" },
    { id: 195, card: "Sophocles", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 196, card: "Mallow", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 197, card: "Lillie", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 198, card: "Decidueye ex", bucket: "Lunala", rarity: "☆☆" },
    { id: 199, card: "Dhelmise ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 200, card: "Incineroar ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 201, card: "Crabominable ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 202, card: "Wishiwashi ex", bucket: "Lunala", rarity: "☆☆" },
    { id: 203, card: "Alolan Raichu ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 204, card: "Lunala ex", bucket: "Lunala", rarity: "☆☆" },
    { id: 205, card: "Passimian ex", bucket: "Lunala", rarity: "☆☆" },
    { id: 206, card: "Alolan Muk ex", bucket: "Lunala", rarity: "☆☆" },
    { id: 207, card: "Solgaleo ex", bucket: "Solgaleo", rarity: "☆☆" },
    { id: 209, card: "Lillie", bucket: "Solgaleo", rarity: "☆☆☆" },
    { id: 210, card: "Bulbasaur", bucket: "Solgaleo", rarity: "✷" },
    { id: 211, card: "Ivysaur", bucket: "Solgaleo", rarity: "✷" },
    { id: 212, card: "Venusaur", bucket: "Solgaleo", rarity: "✷" },
    { id: 214, card: "Exeggutor", bucket: "Lunala", rarity: "✷" },
    { id: 215, card: "Squirtle", bucket: "Lunala", rarity: "✷" },
    { id: 216, card: "Wartortle", bucket: "Lunala", rarity: "✷" },
    { id: 218, card: "Staryu", bucket: "Solgaleo", rarity: "✷" },
    { id: 219, card: "Starmie", bucket: "Solgaleo", rarity: "✷" },
    { id: 220, card: "Gastly", bucket: "Lunala", rarity: "✷" },
    { id: 221, card: "Haunter", bucket: "Lunala", rarity: "✷" },
    { id: 222, card: "Gengar", bucket: "Lunala", rarity: "✷" },
    { id: 223, card: "Machop", bucket: "Solgaleo", rarity: "✷" },
    { id: 224, card: "Machoke", bucket: "Solgaleo", rarity: "✷" },
    { id: 225, card: "Machamp", bucket: "Solgaleo", rarity: "✷" },
    { id: 226, card: "Cubone", bucket: "Lunala", rarity: "✷" },
    { id: 229, card: "Wigglytuff", bucket: "Solgaleo", rarity: "✷" },
    { id: 230, card: "Venusaur ex", bucket: "Solgaleo", rarity: "✷✷" },
    { id: 231, card: "Exeggutor ex", bucket: "Lunala", rarity: "✷✷" },
    { id: 233, card: "Starmie ex", bucket: "Solgaleo", rarity: "✷✷" },
    { id: 234, card: "Gengar ex", bucket: "Lunala", rarity: "✷✷" },
    { id: 236, card: "Marowak ex", bucket: "Lunala", rarity: "✷✷" },
    { id: 237, card: "Wigglytuff ex", bucket: "Solgaleo", rarity: "✷✷" },
    { id: 238, card: "Lunala ex", bucket: "Lunala/Solgaleo", rarity: "♛" }
  ],
  "a2-b": [
    { id: 80, card: "Charizard ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 81, card: "Wugtrio ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 82, card: "Pikachu ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 84, card: "Lucario ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 85, card: "Paldean Clodsire ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 88, card: "Iono", bucket: "Shiny", rarity: "☆☆" },
    { id: 89, card: "Pokemon Center Lady", bucket: "Shiny", rarity: "☆☆" },
    { id: 91, card: "Team Rocket Grunt", bucket: "Shiny", rarity: "☆☆" },
    { id: 92, card: "Pikachu ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 93, card: "Paldean Clodsire ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 94, card: "Tinkaton ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 95, card: "Bibarel ex", bucket: "Shiny", rarity: "☆☆" },
    { id: 96, card: "Giratina ex", bucket: "Shiny", rarity: "☆☆☆" },
    { id: 97, card: "Weedle", bucket: "Shiny", rarity: "✷" },
    { id: 98, card: "Kakuna", bucket: "Shiny", rarity: "✷" },
    { id: 99, card: "Charmander", bucket: "Shiny", rarity: "✷" },
    { id: 101, card: "Wiglett", bucket: "Shiny", rarity: "✷" },
    { id: 102, card: "Dondozo", bucket: "Shiny", rarity: "✷" },
    { id: 103, card: "Pachirisu", bucket: "Shiny", rarity: "✷" },
    { id: 105, card: "Varoom", bucket: "Shiny", rarity: "✷" },
    { id: 106, card: "Revaroom", bucket: "Shiny", rarity: "✷" },
    { id: 107, card: "Beedrill ex", bucket: "Shiny", rarity: "✷✷" },
    { id: 108, card: "Charizard ex", bucket: "Shiny", rarity: "✷✷" },
    { id: 109, card: "Wugtrio ex", bucket: "Shiny", rarity: "✷✷" },
    { id: 110, card: "Lucario ex", bucket: "Shiny", rarity: "✷✷" },
    { id: 111, card: "Poke Ball", bucket: "Shiny", rarity: "♛" }
  ],
  "a2-a": [
    { id: 82, card: "Leafeon ex", bucket: "Arceus", rarity: "☆☆" },
    { id: 84, card: "Garchomp ex", bucket: "Arceus", rarity: "☆☆" },
    { id: 85, card: "Probopass ex", bucket: "Arceus", rarity: "☆☆" },
    { id: 86, card: "Arceus ex", bucket: "Arceus", rarity: "☆☆" },
    { id: 87, card: "Irida", bucket: "Arceus", rarity: "☆☆" },
    { id: 89, card: "Barry", bucket: "Arceus", rarity: "☆☆" },
    { id: 91, card: "Leafeon ex", bucket: "Arceus", rarity: "☆☆" },
    { id: 92, card: "Glaceon ex", bucket: "Arceus", rarity: "☆☆" },
    { id: 94, card: "Probopass ex", bucket: "Arceus", rarity: "☆☆" },
    { id: 95, card: "Arceus ex", bucket: "Arceus", rarity: "☆☆☆" },
    { id: 96, card: "Arceus ex", bucket: "Arceus", rarity: "♛" }
  ],
  "a2": [
    { id: 157, card: "Combee", bucket: "Dialga", rarity: "☆" },
    { id: 158, card: "Carnivine", bucket: "Palkia", rarity: "☆" },
    { id: 159, card: "Shaymin", bucket: "Dialga", rarity: "☆" },
    { id: 160, card: "Mamoswine", bucket: "Dialga", rarity: "☆" },
    { id: 165, card: "Drifloon", bucket: "Dialga", rarity: "☆" },
    { id: 168, card: "Cresselia", bucket: "Palkia", rarity: "☆" },
    { id: 170, card: "Lucario", bucket: "Dialga", rarity: "☆" },
    { id: 173, card: "Croagunk", bucket: "Dialga", rarity: "☆" },
    { id: 177, card: "Bidoof", bucket: "Dialga", rarity: "☆" },
    { id: 178, card: "Glameow", bucket: "Palkia", rarity: "☆" },
    { id: 179, card: "Regigias", bucket: "Dialga", rarity: "☆" },
    { id: 181, card: "Infernape ex", bucket: "Palkia", rarity: "☆☆" },
    { id: 182, card: "Palkia ex", bucket: "Palkia", rarity: "☆☆" },
    { id: 184, card: "Mismagius ex", bucket: "Palkia", rarity: "☆☆" },
    { id: 185, card: "Gallade ex", bucket: "Dialga", rarity: "☆☆" },
    { id: 186, card: "Weavile ex", bucket: "Palkia", rarity: "☆☆" },
    { id: 187, card: "Darkrai ex", bucket: "Dialga", rarity: "☆☆" },
    { id: 189, card: "Lickilicky ex", bucket: "Palkia", rarity: "☆☆" },
    { id: 190, card: "Cyrus", bucket: "Palkia", rarity: "☆☆" },
    { id: 191, card: "Team Galactic Grunt", bucket: "Dialga", rarity: "☆☆" },
    { id: 192, card: "Cynthia", bucket: "Palkia", rarity: "☆☆" },
    { id: 194, card: "Dawn", bucket: "Dialga", rarity: "☆☆" },
    { id: 195, card: "Mars", bucket: "Palkia", rarity: "☆☆" },
    { id: 196, card: "Yanmega ex", bucket: "Dialga", rarity: "☆☆" },
    { id: 197, card: "Infernape ex", bucket: "Palkia", rarity: "☆☆" },
    { id: 198, card: "Pachirisu ex", bucket: "Dialga", rarity: "☆☆" },
    { id: 199, card: "Mismagius ex", bucket: "Palkia", rarity: "☆☆" },
    { id: 200, card: "Gallade ex", bucket: "Dialga", rarity: "☆☆" },
    { id: 201, card: "Weavile ex", bucket: "Palkia", rarity: "☆☆" },
    { id: 202, card: "Darkrai ex", bucket: "Dialga", rarity: "☆☆" },
    { id: 205, card: "Dialga ex", bucket: "Dialga", rarity: "☆☆☆" },
    { id: 206, card: "Palkia ex", bucket: "Dialga/Palkia", rarity: "♛" },
    { id: 207, card: "Dialga ex", bucket: "Dialga/Palkia", rarity: "♛" }
  ],
  "a1-a": [
    { id: 75, card: "Celebi ex", bucket: "Celebi", rarity: "☆☆" },
    { id: 76, card: "Gyarados ex", bucket: "Celebi", rarity: "☆☆" },
    { id: 77, card: "Mew ex", bucket: "Celebi", rarity: "☆☆" },
    { id: 79, card: "Pidgeot ex", bucket: "Celebi", rarity: "☆☆" },
    { id: 80, card: "Budding Exped.", bucket: "Celebi", rarity: "☆☆" },
    { id: 81, card: "Blue", bucket: "Celebi", rarity: "☆☆" },
    { id: 82, card: "Leaf", bucket: "Celebi", rarity: "☆☆" },
    { id: 83, card: "Mew ex", bucket: "Celebi", rarity: "☆☆" },
    { id: 86, card: "Mew ex", bucket: "Celebi", rarity: "♛" }
  ],
  "a1": [
    { id: 251, card: "Venusaur ex", bucket: "Mewtwo", rarity: "☆☆" },
    { id: 253, card: "Charizard ex", bucket: "Charizard", rarity: "☆☆" },
    { id: 255, card: "Moltres ex", bucket: "Charizard", rarity: "☆☆" },
    { id: 257, card: "Starmie ex", bucket: "Charizard", rarity: "☆☆" },
    { id: 258, card: "Articuno ex", bucket: "Mewtwo", rarity: "☆☆" },
    { id: 259, card: "Pikachu ex", bucket: "Pikachu", rarity: "☆☆" },
    { id: 260, card: "Zapdos ex", bucket: "Pikachu", rarity: "☆☆" },
    { id: 261, card: "Gengar ex", bucket: "Mewtwo", rarity: "☆☆" },
    { id: 262, card: "Mewtwo ex", bucket: "Mewtwo", rarity: "☆☆" },
    { id: 264, card: "Marowak ex", bucket: "Mewtwo", rarity: "☆☆" },
    { id: 266, card: "Erika", bucket: "Charizard", rarity: "☆☆" },
    { id: 267, card: "Misty", bucket: "Pikachu", rarity: "☆☆" },
    { id: 268, card: "Blaine", bucket: "Charizard", rarity: "☆☆" },
    { id: 270, card: "Giovanni", bucket: "Mewtwo", rarity: "☆☆" },
    { id: 271, card: "Brock", bucket: "Pikachu", rarity: "☆☆" },
    { id: 272, card: "Sabrina", bucket: "Charizard", rarity: "☆☆" },
    { id: 273, card: "Lt Surge", bucket: "Pikachu", rarity: "☆☆" },
    { id: 274, card: "Moltres ex", bucket: "Charizard", rarity: "☆☆" },
    { id: 275, card: "Articuno ex", bucket: "Mewtwo", rarity: "☆☆" },
    { id: 276, card: "Zapdos ex", bucket: "Pikachu", rarity: "☆☆" },
    { id: 277, card: "Gengar ex", bucket: "Mewtwo", rarity: "☆☆" },
    { id: 278, card: "Machamp ex", bucket: "Charizard", rarity: "☆☆" },
    { id: 279, card: "Wigglytuff ex", bucket: "Pikachu", rarity: "☆☆" },
    { id: 281, card: "Pikachu ex", bucket: "Pikachu", rarity: "☆☆☆" },
    { id: 284, card: "Charizard ex", bucket: "Pika/Char/Mew2", rarity: "♛" },
    { id: 285, card: "Pikachu ex", bucket: "Pika/Char/Mew2", rarity: "♛" },
    { id: 286, card: "Mewtwo ex", bucket: "Pika/Char/Mew2", rarity: "♛" },
  ]

};


